//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace exportrecfile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.126.11;Initial Catalog=I3_IC;User Id=sa;Password=cicadmin;")]
        public string DBConnectString {
            get {
                return ((string)(this["DBConnectString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select cd.callid,convert(varchar,cd.connecteddate,120),convert(varchar,cd.CallDurationSeconds),replace(cd.calleventlog,char(10),' '),cd.customstring1,rc.recordedcallidkey,rd.recordingfilename,rc.recordingid from calldetail as cd left join recordingcall as rc left join recordingdata as rd on rc.recordingid=rd.recordingid on cd.callid=rc.recordedcallidkey where cd.I3TimeStampGMT between dateadd(hh, -9, '{0}') and dateadd(hh, -9, '{1}') and customstring1='{2}'")]
        public string SelectCallDetail {
            get {
                return ((string)(this["SelectCallDetail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800")]
        public int DBTimeOut {
            get {
                return ((int)(this["DBTimeOut"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tishige-VAIO;Initial Catalog=I3_IC;User Id=sa;Password=cicadmin;")]
        public string DBConnectString2 {
            get {
                return ((string)(this["DBConnectString2"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\wavfiles")]
        public string DestinationDirectory {
            get {
                return ((string)(this["DestinationDirectory"]));
            }
            set {
                this["DestinationDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\IW_CIC\\encryptwave-w32r-1-1\\encryptwave-w32r-1-1.exe")]
        public string EncryptExePath {
            get {
                return ((string)(this["EncryptExePath"]));
            }
            set {
                this["EncryptExePath"] = value;
            }
        }
    }
}
